# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1njT8OuhXyyzKSlJvu8WoXY857VuOMxwe
"""

d_ue1 = 10
d_ue2 = 20

d_ue3 = 50
d_ue4 = 100
d_ue4 = 120
d_ue5 = 150
d_ue6 = 70
d_ue7 = 55

power_ue1 = 10**-4/d_ue1**4
power_ue2 = 10**-4/d_ue2**4
power_ue3 = 10**-4/d_ue3**4
power_ue4 = 10**-4/d_ue4**4
power_ue5 = 10**-4/d_ue5**4
power_ue6 = 10**-4/d_ue6**4
power_ue7 = 10**-4/d_ue7**4

sir_ue1_ch1 = power_ue1/power_ue2

sir_ue1_ch2 = power_ue1/power_ue3+power_ue4+power_ue5+power_ue6+power_ue7

print(sir_ue1_ch1)
print(sir_ue1_ch2)